# Generated by Django 4.0.4 on 2022-06-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_task_options_task_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='alarm',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
