# Generated by Django 4.0.4 on 2022-06-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_task_alarm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='alarm',
            field=models.DateTimeField(),
        ),
    ]
