# Generated by Django 4.0.4 on 2022-06-30 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_task_alarm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='alarm',
        ),
    ]
